[project]
name = "filament-inventory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.118.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
]
